### ISSUE TITLE
WebView disappear after device rotation

### ISSUE THREAD

**Issue by calbee633810** [brarcher/rental-calc#40]
Open About dialog and rotate screen, WebView disappears. Even though it's may not be a bug, the app can be more professional and user experience can be improved if WebView persist after screen orientation change.

![screen shot 2018-04-11 at 9 59 55 pm](https://user-images.githubusercontent.com/38213896/38621664-ea993eb0-3dd3-11e8-92fe-4e9220aba7a9.png)
Screenshot before device rotation

![screen shot 2018-04-11 at 10 00 11 pm](https://user-images.githubusercontent.com/38213896/38621688-f2a332fa-3dd3-11e8-80e2-abc7689644e8.png)
Screenshot after device rotation

Tested on Android 23 with Nexus 4 emulator.

**Comment by brarcher** [comment]
Thanks for pointing this out. It should be resolved now, and the fix will appear in the next release.
