### ISSUE TITLE
Cryptographic APIs misuses

### ISSUE THREAD

**Issue by misterAnderson90** [brarcher/rental-calc#49]
I'm a PhD student interested in finding security vulnerabilities in open source projects.

We found a total of 3 warnings (indicating potential vulnerabilities) when running the CogniCrypt static analyzer (*) on rental-calc (or its library dependencies). We documented these issues in private gists for the sake of confidentiality (non-disclosure).

Can you please let us know whether we can share these gists with you? We are eager to evaluate the perception of developers (e.g. severity of these warnings) and improve rental-calc's security, and the quality of the reports of static analysis tools.

(*) https://github.com/CROSSINGTUD/CryptoAnalysis

**Comment by brarcher** [comment]
You are welcome to send me the gists.

**Comment by misterAnderson90** [comment]
Dear Branden,

The CogniCrypt reported 3 warnings related to [chunk-templates](https://github.com/tomj74/chunk-templates/blob/master/src/main/java/com/x5/template/filters/MD5HexFilter.java) and [bumptech/glide](https://github.com/bumptech/glide/blob/d2bb3e8a6a2296b20ecaeb7759c16ef15aacbb28/library/src/main/java/com/bumptech/glide/load/engine/cache/SafeKeyGenerator.java).

[Gist 01 - MessageDigest](https://gist.github.com/misterAnderson90/5f2a932a493139a6c7c1de844411f4a9)
[Gist 02 - MessageDigest](https://gist.github.com/misterAnderson90/dc0ee4b0cb20610bf2ba73dd8b0ebe61)
[Gist 03 - MessageDigest](https://gist.github.com/misterAnderson90/62980e6a696446b8db4eecf6cfd00b4e)


1. How likely might this warning in a third-party library reveal a security threat to this app?
	
   a. Very unlikely;
   
   b. Unlikely;
   
   c. I cannot evaluate this;
   
   d. Likely;
   
   e. Very likely;

Thanks a lot for your collaboration.

**Comment by brarcher** [comment]
> How likely might this warning in a third-party library reveal a security threat to this app?

(a) very unlikely

I do not think that the application uses those APIs directly. If they are used, it would be of a dependency of a dependency. The app does not intentionally do any cryptographic operations as a normal part of its function, nor does it communicate to the Internet.

**Comment by misterAnderson90** [comment]
Thanks for your collaboration, Branden.
